url: http://terrillremodeling.emilymcmahon.com
baseurl: ""

# Nav bar entries
# A new section called XYZ will link to #xyz. You'll need a new file with <section id="xyz"> for this to work properly.
sections:
- name: "Services"
- name: "Portfolio"
- name: "About"
- name: "Estimates"
- name: "Contact"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503   
  secondary-dark: 515151
  muted: 777

image:
  main: /img/header-bg2.jpg

# Font Families
font:
  primary: '"Helvetica Neue",Helvetica,Arial,sans-serif'
  secondary: '"Droid Serif", "Helvetica Neue", Helvetica,Arial,sans-serif'
  color: gray

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
