url: http://terrillremodeling.emilymcmahon.com
baseurl: ""

# Nav bar entries
# A new section called XYZ will link to #xyz. You'll need a new file with <section id="xyz"> for this to work properly.
sections:
- name: "Services"
- name: "Portfolio"
- name: "About"
- name: "Contact"


# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
