url: http://terrillremodeling.emilymcmahon.com
baseurl: ""


# Color, font, etc, changes can be made in _data/template.yml

# Site settings
title: Terrill Remodeling

# Main page header
welcome: "Welcome To Our Workshop!"
welcome2: "Howdy!"
scroll_prompt: "Tell me more"
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Nav bar entries
# Link defaults to xyz.com/#name
sections:
- name: "Services"
- name: "Portfolio"
- name: "About"
- name: "Estimates"
- name: "Contact"

services:
- heading: "Kitchens"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
  icon: fa-cutlery
- heading: "Baths"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
  icon: fa-tint
- heading: "Additions"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
  icon: fa-home

# Portfolio
portfolio:
  # To show all projects in the _data/ folder, just comment out the next line by putting a # in front
  numberFeatured: 3
  seeMoreText: "View All"


# Social networks
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: yelp
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty