url: http://terrillremodeling.emilymcmahon.com
baseurl: ""


# Color, font, etc, changes can be made in _data/template.yml

# Site settings
title: Terrill Remodeling


# Main page header
welcome: "Welcome To Our Workshop!"
welcome2: "Hi!"
scroll_prompt: "Tell me more"
description: "Quality home additions and remodeling contractors serving Janesville, Wisconsin"

# Where should contact messages go. 
# If you change this email address, submit a form and and you'll be prompted to confirm your email. 
# You won't get contacts from the form until your email is confirmed!!!!!
email: mcmahonimal@gmail.com 

# Nav bar entries
# A new section called XYZ will link to #xyz. You'll need a new file with <section id="xyz"> for this to work properly.
sections:
- name: "Services"
- name: "Portfolio"
- name: "About"
- name: "Estimates"
- name: "Contact"

services:
- heading: "Kitchens"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
  icon: fa-cutlery
- heading: "Baths"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
  icon: fa-tint
- heading: "Additions"
  text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
  icon: fa-home


# Team names, titles and social links
people:
- name: Jim Terrill
  pic: jim-team-pic
  position: Owner
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100001245127164

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks
social:
  - title: facebook
    url: https://www.facebook.com/pages/Terrill-Remodeling/1476022199351365


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty