# Site settings
title: Terrill Remodeling

# Main page header
welcome: Welcome to our workshop
welcome2: Howdy!
scroll_prompt: Tell me more
description: Quality home additions and remodeling contractors serving Janesville, Wisconsin

# icon options are listed at terrillremodeling.emilymcmahon.com/img/terrill-icons.jpg
services:
  heading: Come get it!
  categories:
  - heading: Aliens
    text: We come in peace
    icon: child
  - heading: Neighbors
    text: I'm super nosey
    icon: fence
  - heading: Summer Fun
    text: I can't wait
    icon: bbq
  - heading: The throne
    text: I'm a king
    icon: toilet

portfolio:
  heading: A sampling of our latest projects

# Team names, titles and social links
about: 
  heading: 
  body: 

people:
- name: Jim Terrill
  position: Owner
  social:
    - icon: facebook
      url: https://www.facebook.com/profile.php?id=100001245127164

estimates:
  heading: Have a design? Great! We'd love to hear about it!
  body: More stuff

contact:
  heading: Get in touch!
  send: Send!
  emailSubject: new message from your website contact form

# Where should contact messages go. 
# If you change this email address, submit a form and and you'll be prompted to confirm your email. 
# You won't get contacts from the form until your email is confirmed!!!!!
email: terrillremodeling@gmail.com

# Social networks
# Can have anything at http://fontawesome.io/icons/
social:
  - icon: facebook
    url: https://www.facebook.com/pages/Terrill-Remodeling/1476022199351365
  - icon: google
    url: http://www.google.com

# Postal address (add as many lines as necessary)
address:
  - line: 503 E. Holmes St
  - line: Janesville, WI 53545
