# Site settings
title: Terrill Contracting

# Main page header
welcome: Welcome To Our Workshop!
welcome2: Hola!
scroll_prompt: Tell me more
description: Quality home additions and remodeling contractors serving Janesville, Wisconsin

services:
  title: Services
  heading: Lorem ipsum dolor sit amet consectetur.
  categories:
  - heading: Kitchens
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    icon: fa-cutlery
  - heading: Baths
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    icon: fa-tint
  - heading: Additions
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
    icon: fa-home

portfolio:
  title: Portfolio
  heading: Lorem ipsum dolor sit amet consectetur.

# Team names, titles and social links
# The pic is the name of the correct picture at img/team
about: 
  title: About
  heading: Lorem ipsum dolor sit amet consectetur.
  body: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.

people:
- name: Jim Terrill
  pic: jim-team-pic.jpg
  position: Owner
  social:
    - title: facebook #can be facebook / twitter / linkedin or anything else at http://fontawesome.io/icons/
      url: https://www.facebook.com/profile.php?id=100001245127164

#  To add another team member, uncomment the section below by removing each # at the start of each line
#- name: Larry Parker
#  pic: "2.jpg"
#  position: Lead Marketer
#  social:
#   - title: twitter
#     url: #
#   - title: facebook
#      url: #
#    - title: linkedin
#      url: #

estimates:
  title: Estimates
  heading: |
    Have a design? <a href="#contact">Contact us</a> to schedule an estimate! 
  body: |
    Still figuring things out? We can <a href="#contact">recommended quality designers</a> that will help you through the process.

contact:
  title: Contact Us!
  heading: Lorem ipsum dolor sit amet consectetur.
  send: Send Message
  emailSubject: new message from your website contact form

# Where should contact messages go. 
# If you change this email address, submit a form and and you'll be prompted to confirm your email. 
# You won't get contacts from the form until your email is confirmed!!!!!
email: terrillremodeling@gmail.com

# Social networks
# Can have anything at http://fontawesome.io/icons/
social:
  - title: facebook
    url: https://www.facebook.com/pages/Terrill-Remodeling/1476022199351365
  - title: google
    url: 
  - title: yelp
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210
