# Site settings
title: Terrill Remodeling

# Main page header
welcome: Professional home and commercial remodeling in Southern
welcome2: Wisconsin
scroll_prompt: 
description: Quality home additions and remodeling contractors serving Janesville, Wisconsin

# icon options are listed at terrillremodeling.emilymcmahon.com/img/terrill-icons.jpg
services:
  heading: Come get it!
  categories:
  - heading: Aliens
    text: We come in peace
    icon: child
  - heading: Neighbors
    text: I'm super nosey
    icon: fence
  - heading: Summer Fun
    text: I can't wait
    icon: bbq
  - heading: The throne
    text: I'm a king
    icon: toilet

portfolio:
  heading: A sampling of our latest projects

# Team names, titles and social links
about: 
  heading: 
  body: |
    Terrill Remodeling, a third generation remodeling business, has the experience and expertise to bring to your next remodeling project.  Jim Terrill owner, is a licensed contractor who specializes in remodeling of any type.  Jim’s <b>passion</b> for construction and <b>attention to detail</b> make working with Terrill Remodeling a very satisfying experience. 
    <br/><br/>Many contractors can build new.  It takes <b>experience</b> and a <b>special skill set</b> to remodel an existing structure.  Terrill Remodeling will bring our remodeling expertise to your next project.
    <br/><br/>Our mission is to provide <b>customer satisfaction</b> through <b>quality</b> workmanship.  Let us take the ideas that you have for your project and turn them into a <b>beautiful reality</b>.  We have worked extensively throughout Janesville and Rock County and look forward to working with you on your special project.
    <br/><br/>We work with a highly qualified group of licensed subcontractors that we know will work to our standards. 
 

people:
- name: Jim Terrill
  position: Owner
  social:
    - icon: facebook
      url: https://www.facebook.com/profile.php?id=100001245127164

contact:
  heading: Get in touch!
  send: Send!
  emailSubject: new message from your website contact form

# Where should contact messages go. 
# If you change this email address, submit a form and and you'll be prompted to confirm your email. 
# You won't get contacts from the form until your email is confirmed!!!!!
email: terrillremodeling@gmail.com

# Social networks
# Can have anything at http://fontawesome.io/icons/
social:
  - icon: facebook
    url: https://www.facebook.com/pages/Terrill-Remodeling/1476022199351365
  - icon: google
    url: http://www.google.com

# Postal address (add as many lines as necessary)
address:
  - line: 503 E. Holmes St
  - line: Janesville, WI 53545
