# Site settings
title: Terrill Remodeling

# Main page header
welcome: We build your dreams
welcome2: Hello!
scroll_prompt: Go on....
description: Quality home additions and remodeling contractors serving Janesville, Wisconsin

# icon options are listed at http://fontawesome.io/icons/
services:
  heading: We offer many things
  categories:
  - heading: Kitchens
    text: Make me a sandwich
    icon_type: trmdl
    icon: cutlery
  - heading: Bathrooms
    text: "You're stinky"
    icon_type: trmdl
    icon: bath
  - heading: Additions
    text: Not subtractions!
    icon_type: trmdl
    icon: home
  - heading: Decks
    text: Keep neighbors at bay
    icon_type: trmdl
    icon: fence

portfolio:
  heading: A sampling of our latest projects

# Team names, titles and social links
# The pic is the name of the correct picture at img/team
about: 
  heading: 
  body: 

people:
- name: Jim Terrill
  pic: jim-team-pic.jpg
  position: Owner / Operator
  social:
    - icon: facebook #can be facebook / twitter / linkedin or anything else at http://fontawesome.io/icons/
      url: https://www.facebook.com/profile.php?id=100001245127164

estimates:
  heading: |
    Have a design?
    Great! We'd love to hear about it!
  body: 

contact:
  heading: We respond to every message within 24 hours
  send: Send
  emailSubject: new message from your website contact form

# Where should contact messages go. 
# If you change this email address, submit a form and and you'll be prompted to confirm your email. 
# You won't get contacts from the form until your email is confirmed!!!!!
email: terrillremodeling@gmail.com

# Social networks
# Can have anything at http://fontawesome.io/icons/
social:
  - icon: facebook
    url: https://www.facebook.com/pages/Terrill-Remodeling/1476022199351365

# Postal address (add as many lines as necessary)
address:
  - line: 123 Main St.
  - line: Janesville, WI
